[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "embers-passes"
version = "0.1.0"
description = "A lightweight reader and exploration toolkit for calibrated EMBERS satellite pass data."
readme = "README.md"
requires-python = ">=3.13"
license = { text = "MIT" }
authors = [
    { name = "Aman Chokshi" },
]
keywords = [
    "radio astronomy",
    "MWA",
    "satellites",
    "beam calibration",
    "HDF5",
    "embers",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
    "cmasher>=1.9",
    "healpy>=1.16",
    "h5netcdf",
    "h5py",
    "jax",
    "matplotlib>=3",
    "numpy>=2,<2.4",
    "numpyro>=0.21",
    "pymc>=6",
    "pyyaml",
    "scipy>=1.17",
    "zarr>=3",
    "corner>=2.2.3",
    "mwa-jaxbeam>=0.2.0",
    "blackjax>=1.6.2",
    "scikit-learn>=1.9.0",
    "pyuvdata>=3.2.6",
]

[project.urls]
Homepage = "https://github.com/amanchokshi/embers-passes"
Repository = "https://github.com/amanchokshi/embers-passes"
Issues = "https://github.com/amanchokshi/embers-passes/issues"

[dependency-groups]
dev = [
    "ipympl>=0.10.0",
    "ipython>=9.12.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.6",
    "mwa-hyperbeam>=0.10",
    "ruff>=0.15.14",
]

[project.optional-dependencies]
dev = [
    "ipympl>=0.10.0",
    "ipython>=9.12.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.6",
    "mwa-hyperbeam>=0.10",
    "ruff>=0.15.14",
]

[tool.hatch.build.targets.wheel]
packages = ["src/embers_passes"]

[tool.hatch.build.targets.sdist]
include = [
    "src/embers_passes",
    "README.md",
    "pyproject.toml",
    "notebooks",
    "embers_extract",
    "scripts"
]

[tool.uv]
package = true
