# === Required ===
mwa_beamfile: /path/to/beamfile
outdir: /path/to/output
indir: /path/to/input

# === Optional (defaults shown) ===
pol: XX
tile: "06"                 # Leading zero required for single digits
rf_num: 0                  # Which rf explorer to use
num_pass: null             # Use all passes, set to int to use specified number
ndevice: 4                 # Number of cores to use -- number of chains will be set to this
key: 338422580             # Random key for chain initialization
num_warmup: 2000           # Number of warmup samples per chain
num_sample: 4000           # Number of posterior saples to collect per chain
jackknife: false           # Whether to perform a jackknife
jackknife_mode: "time"     # "random" also allowed, will split data in half randomly
jackknife_chunk: 0         # Which jackknife chunk to process (int)
jackknife_key: 224007541   # Key for random jackknifing
ortho_knots: true          # Whether to work in orthographic projection
svi: false                 # Whether to do stochastic variational inference instead of MCMC
enforce_boresight: false   # Enforce that boresight is equal to 1
chunk_sec: 1728000         # How many seconds to chunk data into, default 20 days
dense_mass: false          # Whether to use a dense mass matrix in MCMC
svi_key: 276346727         # Key for SVI initialization
learning_rate: 0.1         # Adam learning rate parameter for SVI
