# === Required ===
mwa_beamfile: /path/to/beamfile
outdir: /path/to/output
indir: /path/to/input

# === Optional (defaults shown) ===
pol: XX
tile: "08"        # Leading zero required for single digits
rf_num: 0
plotting: false
num_pass: null # Use all passes
ndevice: 4
key: 338422580
num_warmup: 1000
num_sample: 2000
mix_model: false
jackknife: false
jackknife_mode: "time" # "random" also allowed
jackknife_chunk: 0
jackknife_key: 224007541
ortho_knots: false
svi: false
enforce_boresight: false
ds_factor: 1
inference: true
postprocess: true
pass_plot_seed: 321906282
chunk_sec: 1728000 # 20 days
dense_mass: false
double_svi: false
svi_key: 276346727